// Models Barrel Export
export * from './condominium.model';
export * from './unit.model';
export * from './resident.model';
export * from './provider.model';
export * from './invoice.model';
export * from './payment.model';
export * from './activity.model';
export * from './notification.model';
export * from './user.model';
export * from './api.model';
export * from './building.model';
export * from './assignment.model';
export * from './fund-type.model';
export * from './payment-config.model';
export * from './fund-config.model';
export * from './fund-movement.model';
